### ISSUE TITLE
Attester Identity in DAA

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/draft-ietf-rats-reference-interaction-models#14]
Based on https://mailarchive.ietf.org/arch/msg/rats/okJriJPpapmZgeOfjbVGVP57bQk/

> Attester Identity ('attesterIdentity'):  _mandatory_
> In DAA, the Attester's identity is not revealed to the verifier.
> The Attester is issued with a credential by the Endorser that is
> randomized and then used to anonymously confirm the validity of
> their evidence.  The evidence is verified using the Endorser's
> public key.

I think here means the DAA credential represents the Attester Identity.

**Comment by henkbirkholz** [comment]
There is ambiguity of “that is randomized”, does it mean randomized Endorser or randomized credential?

**Comment by henkbirkholz** [comment]
For “confirm the validity of their evidence”, what does “their” refer to? And what does “the validity of evidence” mean?

**Comment by Liqun-Chen** [comment]
Yes, the DAA credential represents the Attester's identity.

The DAA credential is randomised so that it is not revealed when providing the Attestation evidence to the verifier. The Endorser is not randomised. 

To make it clear "the validity of their evidence" can be changed to "the validity of the Attester's evidence". The validity of evidence means that the evidence provided by the Attester to the verifier is confirmed to be true.

**Comment by henkbirkholz** [comment]
Moved to draft-birkholz-rats-daa
